image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # установка образа docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

build_script:
  - sudo docker-compose up -d
  - sleep 20

  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar aqa-shop.jar & 
  - sleep 20

  - chmod +x ./gradlew
  - ./gradlew clean test -Ddb.url=jdbc:mysql://localhost:3306/app -Dselenide.headless=true --info
